### ISSUE TITLE
PARALLEL RESIDUAL BI-FUSION FEATURE PYRAMID NETWORK FOR ACCURATE SINGLE-SHOT OBJECT DETECTION

### ISSUE THREAD

**Issue by xiaozhangya** [PingYangChen/globpso#1]
Are you the author of this paper? Is the paper open source? I'm very interested in the work. Hope to get the author's reply! Thank you very much.

**Comment by PingYangChen** [comment]
Please stop posting irrelevant issues. Appreciate that!
