### ISSUE TITLE
Problem with installation windows 11, R version 4.3.2 (2023-10-31 ucrt) -- "Eye Holes" Copyright (C) 2023 The R Foundation for Statistical Computing Platform: x86_64-w64-mingw32/x64 (64-bit)

### ISSUE THREAD

**Issue by kis81** [PingYangChen/globpso#2]
pak::pkg_install("PingYangChen/globpso",dependencies = TRUE)
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
✔ Loading metadata database ... done                             
                                                                            
→ Will install 1 package.
→ Will download 1 package with unknown size.
+ globpso   1.1.1 [bld][cmp][dl] (GitHub: 0c941a2)
ℹ Getting 1 pkg with unknown size
✔ Cached copy of globpso 1.1.1 (source) is the latest build
✔ No downloads needed, all packages are cached                      
ℹ Building globpso 1.1.1
✖ Failed to build globpso 1.1.1                                    
Error:                                                             
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package globpso.
Type .Last.error to see the more details.

 .Last.error
<callr_error/rlib_error_3_0/rlib_error/error>
Error: 
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package globpso.
---
Backtrace:
1. pak::pkg_install("PingYangChen/globpso", dependencies = TRUE)
2. pak:::remote(function(...) get("pkg_install_do_plan", asNamespace("pak"))(...), …
3. err$throw(res$error)
---
Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("pkg_install_do_plan", asNamespace("pak"))(...)
 3. proposal$install()
 4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
 5. base::withCallingHandlers({ …
 6. pkgdepends:::handle_events(state, events)
 7. pkgdepends:::handle_event(state, i)
 8. pkgdepends:::stop_task(state, worker)
 9. pkgdepends:::stop_task_build(state, worker)
10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
11. | base::signalCondition(cond)
12. global (function (e) …

**Comment by PingYangChen** [comment]
Unfortunately, I couldn't replicate the error on a machine running Windows 11 OS with R version 4.3.2.

The current release of `globpso` is designed to work seamlessly on Windows OS. To troubleshoot the issue, kindly verify if Rtools 4.3 is installed. You can download it from https://cran.r-project.org/bin/windows/Rtools/. Post-installation, ensure that the path "C:\rtools43\mingw64\bin" is included in the PATH environment variable of your OS.

**Comment by kis81** [comment]
Thanks, but Rtools 4.3 is installed and PATH is ok.  I have also tried devtools with error:

devtools::install_github("PingYangChen/globpso",dependencies = TRUE)
Downloading GitHub repo PingYangChen/globpso@HEAD
Registered S3 methods overwritten by 'callr':
  method                    from
  format.callr_status_error     
  print.callr_status_error      
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\docMgrJozefKiseľákPh\AppData\Local\Temp\RtmpacuPJG\remotesa3420672872\PingYangChen-globpso-0c941a2/DESCRIPTION'
─  preparing 'globpso':
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'globpso_1.1.1.tar.gz'
   
Installing package into ‘C:/Users/docMgrJozefKiseľákPh/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
* installing *source* package 'globpso' ...
** using staged installation
** libs
using C++ compiler: 'G__~1.EXE (GCC) 12.3.0'
g++ -std=gnu++17  -I"C:/PROGRA~1/R/R-43~1.2/include" -DNDEBUG  -I'C:/Users/docMgrJozefKiseľákPh/AppData/Local/R/win-library/4.3/Rcpp/include' -I'C:/Users/docMgrJozefKiseľákPh/AppData/Local/R/win-library/4.3/RcppArmadillo/include'   -I"C:/RBuildTools/4.3/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:4:10: fatal error: RcppArmadillo.h: No such file or directory
    4 | #include <RcppArmadillo.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-43~1.2/etc/x64/Makeconf:272: RcppExports.o] Error 1
ERROR: compilation failed for package 'globpso'
* removing 'C:/Users/docMgrJozefKiseľákPh/AppData/Local/R/win-library/4.3/globpso'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/DOCMGR~1/AppData/Local/Temp/RtmpacuPJG/filea3415fb718e/globpso_1.1.1.tar.gz’ had non-zero exit status

**Comment by PingYangChen** [comment]
Would you please check whether the package `RcppArmadillo` is properly installed?

You can try running the following codes in R and see if the `obj_c` is compiled smoothly.
```
library(Rcpp)
library(RcppArmadillo)

objf_c <- cppFunction('double objf_c(SEXP x, SEXP a) {
  double a_c = (double)Rcpp::as<double>(a);
  arma::rowvec x_c = (arma::rowvec)Rcpp::as<arma::rowvec>(x);
  arma::uword n = x_c.n_elem;
  double n_double = (double)n;
  double pi_val = 3.14159265358979311600;
  double val = n_double*a_c;
  for (arma::uword i = 0; i < n; i++) {
    val += ( x_c(i)*x_c(i) - a_c*std::cos(2.*pi_val*x_c(i)) );
  }
  return val;
 }', depends = "RcppArmadillo")

print(objf_c(rep(0, 2), 10))
# 0
```

**Comment by kis81** [comment]
> library(Rcpp)
> library(RcppArmadillo)
> objf_c <- cppFunction('double objf_c(SEXP x, SEXP a) {
+   double a_c = (double)Rcpp::as<double>(a);
+   arma::rowvec x_c = (arma::rowvec)Rcpp::as<arma::rowvec>(x);
+   arma::uword n = x_c.n_elem;
+   double n_double = (double)n;
+   double pi_val = 3.14159265358979311600;
+   double val = n_double*a_c;
+   for (arma::uword i = 0; i < n; i++) {
+     val += ( x_c(i)*x_c(i) - a_c*std::cos(2.*pi_val*x_c(i)) );
+   }
+   return val;
+  }', depends = "RcppArmadillo")
using C++ compiler: 'G__~1.EXE (GCC) 12.3.0'
using C++11
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.2/include" -DNDEBUG -I../inst/include -fopenmp  -I"C:/Users/docMgrJozefKiseľákPh/AppData/Local/R/win-library/4.3/Rcpp/include" -I"C:/Users/docMgrJozefKiseľákPh/AppData/Local/R/win-library/4.3/RcppArmadillo/include" -I"C:/Users/docMgrJozefKiseľákPh/AppData/Local/Temp/RtmpacuPJG/sourceCpp-x86_64-w64-mingw32-1.0.12"   -I"C:/RBuildTools/4.3/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c filea347d1e1dd6.cpp -o filea347d1e1dd6.o
filea347d1e1dd6.cpp:3:10: fatal error: RcppArmadillo.h: No such file or directory
    3 | #include <RcppArmadillo.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-43~1.2/etc/x64/Makeconf:272: filea347d1e1dd6.o] Error 1
Error in sourceCpp(code = code, env = env, rebuild = rebuild, cacheDir = cacheDir,  : 
  Error 1 occurred building shared library.

**Comment by PingYangChen** [comment]
The error message shows that g++ could not find the RcppArmadillo header file, `RcppArmadillo.h`. Please make sure the RcppArmadillo has been installed properly.

I have noticed that the path, `C:/Users/docMgrJozefKiseľákPh/AppData/Local/R/win-library/4.3/RcppArmadillo/include`, where the packages are installed, includes special characteristics such as `á`.  It may cause the failure when compiling C/C++ codes with g++. Please try to install your R and related packages under another path.
